<?php

namespace HDW\MongoDBBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * DevRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class DevRepository extends DocumentRepository
{
    public function findIn2017()
    {
       return $this->createQueryBuilder('Dev')
           ->field('startingdate')
           ->
           ->gte(2017-01-01)
           ->lte(2017-12-31)
           ->range(2017-01-01,2017-12-31)
           ->getQuery()
           ->execute()
           ;
    }

.find({$and: [{"startingdate": {$gte: ISODate("2017-01-01 00:00:00.000Z")}},{"startingdate": {$lte: ISODate("2017-12-31 00:00:00.000Z")}}]})
}
