<?php

namespace HDW\MySQLBundle\Repository;

/**
 * DeveloperRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use HDW\MainBundle\Repository\I_DeveloperRepository;
use HDW\MySQLBundle\Entity\Developer;

class DeveloperRepository extends EntityRepository implements I_DeveloperRepository
{
    public function findIn2017()
    {
        $qb = $this->createQueryBuilder('a');

        $this->whereCurrentYear($qb);

        return $qb->getQuery()->getResult();
    }

    public function whereCurrentYear(QueryBuilder $qb)
    {
        $qb ->andWhere('a.startingdate BETWEEN :start AND :end')
            ->setParameter('start', new \Datetime(date('Y').'-01-01'))
            ->setParameter('end',   new \Datetime(date('Y').'-12-31'))
        ;
    }

    public function findStagiaire()
    {
        $qb = $this->createQueryBuilder('a');
        $qb->where('a.state = :etat')->setParameter('etat','Stagiaire');

        return $qb->getQuery()->getResult();
    }

    public function findDevMontpellier()
    {
        $qb = $this->createQueryBuilder('a')->leftJoin('a.city','city')->addSelect('city');
        $qb->where('city.name = :nom')->setParameter('nom','Montpellier');
        return $qb->getQuery()->getResult();
    }

    public function findProjetsDev()
    {
        $query = $this->_em->createQuery('SELECT a FROM HDW\MySQLBundle\Entity\Developer a
                                                        JOIN HDW\MySQLBundle\Entity\DeveloperProjet b 
                                                        WHERE a.id = b.developer
                                                        JOIN HDW\MySQLBundle\Entity\Projet c 
                                                        WHERE b.projet = c.id
                                                        AND c.name = :name');
        $query->setParameter('name','Gagné les Championnats du Monde 2017');
        $results = $query->getResult();

        return $results;
    }
}
