<?php

namespace HDW\MySQLBundle\Repository;

/**
 * DeveloperRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use HDW\MainBundle\Repository\I_DeveloperRepository;

class DeveloperRepository extends EntityRepository implements I_DeveloperRepository
{
    public function findIn2017()
    {
        $qb = $this->createQueryBuilder('a');

        $this->whereCurrentYear($qb);

        return $qb->getQuery()->getResult();
    }

    public function whereCurrentYear(QueryBuilder $qb)
    {
        $qb ->andWhere('a.startingdate BETWEEN :start AND :end')
            ->setParameter('start', new \Datetime(date('Y').'-01-01'))
            ->setParameter('end',   new \Datetime(date('Y').'-12-31'))
        ;
    }

    public function findStagiaire()
    {
        $qb = $this->createQueryBuilder('a');
        $qb->where('a.state = :etat')->setParameter('etat','Stagiaire');

        return $qb->getQuery()->getResult();
    }
}
